language: c
services: PostgreSQL

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh r_binary_install ggplot2
  - ./travis-tool.sh r_binary_install RSQLite
  - ./travis-tool.sh r_binary_install RMySQL
  - ./travis-tool.sh r_binary_install rgl
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh r_binary_install knitr
  - ./travis-tool.sh github_package hadley/hflights
  - ./travis-tool.sh github_package bigrquery
  - ./travis-tool.sh install_deps

before_script:
- psql -c 'create database lahman;' -U postgres
- psql -c 'create database hflights;' -U postgres
- psql -c 'create database test;' -U postgres
# Install dplyr package then cache sqlite and postgres version of Lahman
- R CMD INSTALL .
- Rscript -e "library(dplyr); lahman_sqlite(); lahman_postgres()"
- Rscript -e "library(dplyr); hflights_postgres(); hflights_sqlite()"
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

branches:
  except:
  - /-expt$/
notifications:
  email:
    on_success: change
    on_failure: change

